In [2]:
import numpy as np

In [9]:
inputs = np.load("data/sudoku-extreme-1k-aug-1000-hint/train/all__inputs.npy")
print(inputs[0].reshape(9, 9)-1)
print(inputs[1].reshape(9, 9)-1)

[[0 0 5 0 2 0 0 8 0]
 [0 7 0 0 0 0 3 0 4]
 [0 0 0 7 0 1 0 0 2]
 [0 0 0 0 7 3 0 0 0]
 [4 8 1 0 0 0 5 0 0]
 [0 5 0 0 0 0 0 0 6]
 [0 0 0 0 4 0 6 0 1]
 [0 0 8 0 0 6 0 3 0]
 [0 0 0 0 0 5 0 0 0]]
[[0 0 5 3 2 4 0 8 0]
 [0 7 0 6 0 9 3 5 4]
 [0 3 4 7 5 1 9 6 2]
 [0 2 0 0 7 3 0 1 0]
 [4 8 1 9 0 0 5 7 3]
 [0 5 7 0 0 0 0 9 6]
 [0 0 0 0 4 0 6 2 1]
 [0 4 8 0 0 6 7 3 0]
 [7 1 0 0 0 5 8 4 0]]
